const PDFDocument = require('pdfkit');

function generateReport(analysis, settings = {}) {
  const doc = new PDFDocument({ margin: 50 });
  const company = settings.company_name || 'SpecMatch';
  const { project_name, spec_filename, created_at, results } = analysis;
  const ranked = results?.rankedProducts || [];

  // Cover page
  doc.fontSize(28).font('Helvetica-Bold').text('SpecMatch Analysis Report', { align: 'center' });
  doc.moveDown(0.5);
  doc.fontSize(14).font('Helvetica').text(`Project: ${project_name || 'Untitled'}`, { align: 'center' });
  doc.text(`Spec File: ${spec_filename || '—'}`, { align: 'center' });
  doc.text(`Date: ${created_at ? created_at.slice(0, 10) : new Date().toISOString().slice(0, 10)}`, { align: 'center' });
  doc.text(`Prepared by: ${company}`, { align: 'center' });
  doc.moveDown(2);
  doc.addPage();

  // Results
  doc.fontSize(20).font('Helvetica-Bold').text('Matched Products');
  doc.moveDown(1);

  if (ranked.length === 0) {
    doc.fontSize(12).font('Helvetica').text('No products were matched against this specification.');
  }

  ranked.forEach((p, i) => {
    doc.fontSize(14).font('Helvetica-Bold').text(`${i + 1}. ${p.productName || p.tdsId}`);
    doc.fontSize(11).font('Helvetica').text(`Score: ${p.score || 0}/100 — ${p.rating || ''}`, { indent: 20 });
    if (p.summary) doc.text(`Summary: ${p.summary}`, { indent: 20 });
    if (p.meets?.length) doc.text(`Meets: ${p.meets.join('; ')}`, { indent: 20 });
    if (p.shortfalls?.length) doc.text(`Gaps: ${p.shortfalls.join('; ')}`, { indent: 20 });
    if (p.exceedances?.length) doc.text(`Exceedances: ${p.exceedances.join('; ')}`, { indent: 20 });
    doc.moveDown(0.5);
    if (i < ranked.length - 1) {
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
      doc.moveDown(0.5);
    }
  });

  doc.moveDown(2);
  doc.fontSize(9).fillColor('#888888')
    .text('Citations generated by SpecMatch against project manual · All matches reviewed by preparer', { align: 'center' });

  return doc;
}

module.exports = { generateReport };
